name: Olay Düzenle
description: Mevcut bir olayı düzenleyin
title: "Olay Düzenle"
labels: ["upgrade-event"]
assignees:
  - sergenaras
body:
  - type: markdown
    attributes:
      value: |
        ## Mevcut Olayı Düzenleyin
        ⚠️ **NOT:** Bu form sadece mevcut bir olayı düzenlemek içindir. Dosya adı otomatik olarak korunacaktır.
        
  - type: input
    id: date
    attributes:
      label: "Tam Tarih (YYYY-AA-GG) *"
      description: Olayın gerçekleştiği tam tarih.
      placeholder: "Örnek: 2024-10-24"
    validations:
      required: true

  - type: input
    id: time
    attributes:
      label: "Saat (SS:DD) - İsteğe bağlı"
      description: Olayın gerçekleştiği tam saat (24 saat formatında).
      placeholder: "Örnek: 14:30"
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: "Kategori *"
      description: Olayın ana kategorisi.
      options:
        - teknoloji
        - bilim
        - tarih
        - kültür
        - spor
        - politika
        - diğer
    validations:
      required: true

  - type: input
    id: other_category
    attributes:
      label: "Özel Kategori (Eğer 'Diğer' Seçtiyseniz)"
      description: Kategori listesinden "Diğer"i seçtiyseniz, lütfen özel kategorinizi buraya girin.
      placeholder: "Örn: Arkeoloji"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "Olay Açıklaması *"
      description: |
        Olayın detaylı açıklaması. 
        **İLK CÜMLE OTOMATİK OLARAK BAŞLIK OLARAK KULLANILACAKTIR.**
        Lütfen ilk cümleyi başlık gibi yazın.
      placeholder: "Olayın detaylı açıklamasını buraya yazın..."
    validations:
      required: true

  - type: textarea
    id: sources
    attributes:
      label: "Kaynaklar *"
      description: Olayı doğrulayan kaynak(lar) için URL ekleyin.
      placeholder: |
        - https://www.resmikaynak.gov/....
        - https://www.habersitesi.com/....
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "Doğrulama Kontrol Listesi *"
      description: Göndermeden önce lütfen onaylayın.
      options:
        - label: Tarih formatının (YYYY-AA-GG) doğru olduğundan eminim.
          required: true
        - label: Güvenilir kaynaklar ekledim.
          required: true