name: Fallback Event
description: Manuel olay ekleme/düzenleme (JSON sistemi çalışmazsa)
title: "Fallback Event"
labels: ["manual-event"]
body:
  - type: textarea
    id: manual_data
    attributes:
      label: Manuel Veri
      description: Eğer JSON sistemi çalışmazsa bu alanı kullanın
      placeholder: |
        Başlık: Örnek Olay
        Tarih: 2024-01-01
        Kategori: teknoloji
        Açıklama: Örnek açıklama
        Kaynaklar: - https://example.com