name: Yeni Olay Ekle
description: Zaman çizelgesine yeni bir olay ekleyin
title: "Yeni Olay: "
labels: ["new-event"]
assignees:
  - sergenaras
body:
  - type: markdown
    attributes:
      value: |
        ## Zaman Çizelgesine Yeni Olay Ekleyin
        Lütfen tüm alanları dikkatlice doldurun. Girilen verilerin kalitesi, zaman çizelgesinin doğruluğu için kritiktir.
        
  # --- DEĞİŞTİRİLEN SATIR ---
  - type: input
    id: event_title # <-- 'title' idi, 'event_title' olarak değiştirildi
    attributes:
      label: Başlık
      description: Olay başlığı (kısa ve öz)
      placeholder: "Örnek: Yapay Zeka Devrimi"
    validations:
      required: true
  # -------------------------

  - type: input
    id: date
    attributes:
      label: Tam Tarih (YYYY-AA-GG)
      description: |
        Olayın gerçekleştiği tam tarih. Eğer gün ve ay bilinmiyorsa, lütfen yılın ilk gününü girin (Örn: 2024-01-01).
      placeholder: "Örnek: 2024-10-24"
    validations:
      required: true

  - type: input
    id: time
    attributes:
      label: Saat (SS:DD) - İsteğe bağlı
      description: |
        Olayın gerçekleştiği tam saat (24 saat formatında). 
        Bu alanı doldurmak, olayın zaman çizelgesinde (x4) saat hassasiyetinde görünmesini sağlar.
      placeholder: "Örnek: 14:30"
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Kategori
      description: Olayın ana kategorisi. "Diğer" seçerseniz, lütfen aşağıdaki "Özel Kategori" alanını doldurun.
      options:
        - teknoloji
        - bilim
        - tarih
        - kültür
        - spor
        - politika
        - diğer
    validations:
      required: true

  - type: input
    id: other_category
    attributes:
      label: Özel Kategori (Eğer 'Diğer' Seçtiyseniz)
      description: Kategori listesinden "Diğer"i seçtiyseniz, lütfen özel kategorinizi buraya girin.
      placeholder: "Örn: Arkeoloji"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Açıklama
      description: Olay hakkında 1-2 cümlelik detaylı açıklama. Bu, "Olay Detayları" panelinde görünecektir.
      placeholder: "Olayın detaylı açıklamasını buraya yazın..."
    validations:
      required: true

  - type: textarea
    id: sources
    attributes:
      label: Kaynaklar
      description: |
        Lütfen olayı doğrulayan kaynak(lar) için URL ekleyin.
        - **Resmi Kaynak:** (Örn: Resmi Gazete, TÜİK, NASA.gov) 1 adet kaynak yeterlidir.
        - **Resmi Olmayan Kaynak:** (Örn: Haber siteleri, Wikipedia) Lütfen en az 2 farklı kaynaktan doğrulama ekleyin.
      placeholder: |
        - https://www.resmikaynak.gov/....
        - https://www.habersitesi.com/....
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Doğrulama Kontrol Listesi
      description: Göndermeden önce lütfen onaylayın.
      options:
        - label: Tarih formatının (YYYY-AA-GG) doğru olduğundan eminim.
          required: true
        - label: Güvenilir kaynaklar ekledim.
          required: true